/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/iniciarsesion` | `/iniciarsesion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recuperarcontrasenia` | `/recuperarcontrasenia`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registrarse` | `/registrarse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(campanas)'}/DetalleCampana` | `/DetalleCampana`; params?: Router.UnknownInputParams; } | { pathname: `${'/(campanas)'}/UltimasDonaciones` | `/UltimasDonaciones`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Campanas` | `/Campanas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/iniciarsesion` | `/iniciarsesion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/recuperarcontrasenia` | `/recuperarcontrasenia`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/registrarse` | `/registrarse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(campanas)'}/DetalleCampana` | `/DetalleCampana`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(campanas)'}/UltimasDonaciones` | `/UltimasDonaciones`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Campanas` | `/Campanas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/iniciarsesion${`?${string}` | `#${string}` | ''}` | `/iniciarsesion${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/recuperarcontrasenia${`?${string}` | `#${string}` | ''}` | `/recuperarcontrasenia${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/registrarse${`?${string}` | `#${string}` | ''}` | `/registrarse${`?${string}` | `#${string}` | ''}` | `${'/(campanas)'}/DetalleCampana${`?${string}` | `#${string}` | ''}` | `/DetalleCampana${`?${string}` | `#${string}` | ''}` | `${'/(campanas)'}/UltimasDonaciones${`?${string}` | `#${string}` | ''}` | `/UltimasDonaciones${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Campanas${`?${string}` | `#${string}` | ''}` | `/Campanas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/iniciarsesion` | `/iniciarsesion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recuperarcontrasenia` | `/recuperarcontrasenia`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registrarse` | `/registrarse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(campanas)'}/DetalleCampana` | `/DetalleCampana`; params?: Router.UnknownInputParams; } | { pathname: `${'/(campanas)'}/UltimasDonaciones` | `/UltimasDonaciones`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Campanas` | `/Campanas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
    }
  }
}
